// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGAufWgrJYYcEICJfdh0XqEfGLqaWphc8',
    appId: '1:466530259496:web:600200d2594be9fb1b9b1d',
    messagingSenderId: '466530259496',
    projectId: 'jgs-store',
    authDomain: 'jgs-store.firebaseapp.com',
    storageBucket: 'jgs-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqR7ihUwinfbT0eFWrlDMmafxcx_WgY8M',
    appId: '1:466530259496:android:39f6b2d5bd9a27a51b9b1d',
    messagingSenderId: '466530259496',
    projectId: 'jgs-store',
    storageBucket: 'jgs-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDImol_9i7Fcn2_6uQGQkwTGtuGB3wL5yw',
    appId: '1:466530259496:ios:63af3268845fe4661b9b1d',
    messagingSenderId: '466530259496',
    projectId: 'jgs-store',
    storageBucket: 'jgs-store.firebasestorage.app',
    iosBundleId: 'com.jagdishgeneralstore.jgs',
  );
}
